ALTER TABLE "GES" ADD COLUMN IF NOT EXISTS "renewableEnergyTargetPercent" DOUBLE PRECISION;
ALTER TABLE "GES" ADD COLUMN IF NOT EXISTS "sanctionedLoadKw" DOUBLE PRECISION;
ALTER TABLE "GES" ADD COLUMN IF NOT EXISTS "solarConnectionType" TEXT;
ALTER TABLE "GES" ADD COLUMN IF NOT EXISTS "peakRecordedDemandKva" DOUBLE PRECISION;
ALTER TABLE "GES" ADD COLUMN IF NOT EXISTS "bessRequirement" TEXT;
